# Generated by Django 5.2.9 on 2026-01-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='stock_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
