# Generated by Django 5.2.9 on 2025-12-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
