# Generated by Django 5.2.9 on 2026-01-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_catalogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmodel',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='catalogs/pdfs/'),
        ),
    ]
