# Generated by Django 5.2.9 on 2026-01-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='title_font_family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
