# Generated by Django 5.2.9 on 2026-01-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_landingpage_title_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='description_en',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
