# Generated by Django 5.2.9 on 2025-12-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_referencecategory_referencemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='for_project',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
