# Generated by Django 5.2.9 on 2026-02-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_bannerimagemodel_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerimagemodel",
            name="link_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
