# Generated by Django 5.2.9 on 2026-02-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_bannerimagemodel_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_eng",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_eng",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
