# Generated by Django 5.2.9 on 2026-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_category_description_eng_category_name_eng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
