# Generated by Django 5.2.9 on 2026-02-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_products_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
