# Generated by Django 5.2.9 on 2026-06-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_products_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPageBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("public_id", models.CharField(blank=True, max_length=255, null=True)),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="products.landingpage",
                    ),
                ),
            ],
        ),
    ]
