# Generated by Django 5.2.9 on 2025-12-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
