# Generated by Django 5.2.9 on 2026-06-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
    ]
